export const BASE = '/p/atelier'

export const NAV = [
  { to: '', label: 'Collections', path: 'collections' },
  { to: 'lookbook', label: 'Lookbook', path: 'lookbook' },
  { to: 'about', label: 'Maison', path: 'about' },
  { to: 'contact', label: 'Contact', path: 'contact' },
]

export const PRODUCTS = [
  {
    id: 1,
    name: 'Camel Overcoat',
    category: 'Outerwear',
    price: 2850,
    seed: 'atelier-coat-1',
    seed2: 'atelier-coat-1b',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'A masterwork in double-faced camel hair, cut with architectural precision. The structured shoulder meets a gently tapered silhouette — a coat for decades, not seasons.',
  },
  {
    id: 2,
    name: 'Alpaca Cocoon Coat',
    category: 'Outerwear',
    price: 3400,
    seed: 'atelier-coat-2',
    seed2: 'atelier-coat-2b',
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Woven in Peru from single-origin baby alpaca. The cocoon silhouette drapes effortlessly, weight dissolving at the shoulder. A study in softness.',
  },
  {
    id: 3,
    name: 'Ribbed Cashmere Turtleneck',
    category: 'Knitwear',
    price: 980,
    seed: 'atelier-knit-1',
    seed2: 'atelier-knit-1b',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Grade-A Scottish cashmere, hand-finished at our Edinburgh mill. The fine-gauge rib adapts to the body with quiet intelligence.',
  },
  {
    id: 4,
    name: 'Merino Blanket Cardigan',
    category: 'Knitwear',
    price: 1240,
    seed: 'atelier-knit-2',
    seed2: 'atelier-knit-2b',
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Oversized and enveloping, this cardigan moves between interior ease and exterior polish. Crafted from extra-fine Merino with an open, airy hand.',
  },
  {
    id: 5,
    name: 'Chalk Stripe Blazer',
    category: 'Tailoring',
    price: 2200,
    seed: 'atelier-suit-1',
    seed2: 'atelier-suit-1b',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Cut from a Loro Piana Super 130s wool in a heritage chalk stripe. Soft construction through the chest allows the cloth to breathe and move naturally.',
  },
  {
    id: 6,
    name: 'Ivory Tuxedo Trouser',
    category: 'Tailoring',
    price: 890,
    seed: 'atelier-suit-2',
    seed2: 'atelier-suit-2b',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'A high-rise, wide-leg trouser in pure ivory wool with a silk satin side stripe. Elevated enough for evening, considered enough for day.',
  },
  {
    id: 7,
    name: 'Woven Leather Belt',
    category: 'Accessories',
    price: 345,
    seed: 'atelier-acc-1',
    seed2: 'atelier-acc-1b',
    sizes: ['S/M', 'M/L', 'L/XL'],
    description: 'Intricately woven from vegetable-tanned Italian nappa. Each belt is hand-assembled over four hours by a single artisan.',
  },
  {
    id: 8,
    name: 'Silk Scarf — Botanical',
    category: 'Accessories',
    price: 420,
    seed: 'atelier-acc-2',
    seed2: 'atelier-acc-2b',
    sizes: ['One Size'],
    description: 'Printed on 14mm habotai silk with pigments sourced from botanical extracts. Hand-rolled edges. Each piece numbered from a limited edition of 200.',
  },
  {
    id: 9,
    name: 'Cashmere Boucle Coat',
    category: 'Outerwear',
    price: 4100,
    seed: 'atelier-coat-3',
    seed2: 'atelier-coat-3b',
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'A sculptural boucle woven in Florence from cashmere and organic cotton. The looped texture catches light; the silhouette remains rigorously clean.',
  },
  {
    id: 10,
    name: 'Lambswool Roll-neck',
    category: 'Knitwear',
    price: 760,
    seed: 'atelier-knit-3',
    seed2: 'atelier-knit-3b',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Our classic roll-neck, annually refined. Lambswool from Shetland, dyed in small batches with natural pigment at our mill in the Scottish Borders.',
  },
  {
    id: 11,
    name: 'Deconstructed Suit Jacket',
    category: 'Tailoring',
    price: 1850,
    seed: 'atelier-suit-3',
    seed2: 'atelier-suit-3b',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'The jacket reimagined without interlining or padding. Pure cloth, pure construction — the wearer shapes it over time.',
  },
  {
    id: 12,
    name: 'Suede Gloves',
    category: 'Accessories',
    price: 280,
    seed: 'atelier-acc-3',
    seed2: 'atelier-acc-3b',
    sizes: ['6.5', '7', '7.5', '8'],
    description: 'Peccary suede gloves cut by a third-generation gantier in Millau, France. The world\'s finest glove-making tradition, unbroken.',
  },
]

export const LOOKBOOK = [
  {
    id: 1,
    figNum: '01',
    title: 'Dissolution',
    caption: 'The boundary between fabric and air. Alpaca and silk organza layer over a sculpted trouser — worn as armour, experienced as surrender.',
    seed: 'lookbook-atelier-1',
    w: 900,
    h: 1200,
  },
  {
    id: 2,
    figNum: '02',
    title: 'The Weight of Cloth',
    caption: 'Double-faced camel hair falling from the shoulder in a single uninterrupted arc. There are no seams where the eye expects them.',
    seed: 'lookbook-atelier-2',
    w: 900,
    h: 1200,
  },
  {
    id: 3,
    figNum: '03',
    title: 'Architecture',
    caption: 'The blazer without apology. Chalk stripe Loro Piana, cut for a woman who has decided. The sleeve has one button undone — always.',
    seed: 'lookbook-atelier-3',
    w: 900,
    h: 1200,
  },
  {
    id: 4,
    figNum: '04',
    title: 'Still Life',
    caption: 'Ivory tuxedo trousers and nothing else but the scarf knotted loosely. Evening begins at the dressing table with this kind of certainty.',
    seed: 'lookbook-atelier-4',
    w: 900,
    h: 1200,
  },
  {
    id: 5,
    figNum: '05',
    title: 'Grain',
    caption: 'Boucle up close is a world entire: loops of cashmere in four tones, the smallest gesture multiplied across the body into texture that reads as warmth.',
    seed: 'lookbook-atelier-5',
    w: 900,
    h: 1200,
  },
  {
    id: 6,
    figNum: '06',
    title: 'Undone',
    caption: 'The roll-neck pulled high, the lambswool pressed against the jaw. Winter as intimacy. Winter as refusal to leave the house poorly dressed.',
    seed: 'lookbook-atelier-6',
    w: 900,
    h: 1200,
  },
]

export const TIMELINE = [
  {
    year: '1987',
    title: 'Founded in Lyon',
    text: 'Isabelle Faure opens a small atelier on Rue Auguste Comte with a single sewing machine, six yards of English wool, and an uncompromising conviction about how clothes should be made.',
  },
  {
    year: '1993',
    title: 'First Collection',
    text: 'The debut collection — twelve pieces — is shown to forty invited guests in the atelier. All twelve pieces sell within the week. International editors take note.',
  },
  {
    year: '2001',
    title: 'London Boutique',
    text: 'ATELIER opens on Mount Street, Mayfair. The space is designed with architect Hideo Mori: pale stone, natural linen, considered light. Clothing displayed like sculpture.',
  },
  {
    year: '2008',
    title: 'Mill Acquisition',
    text: 'We acquire a 19th-century mill in the Scottish Borders to produce our own cashmere and lambswool yarns — full control of the fibre from fleece to finished garment.',
  },
  {
    year: '2015',
    title: 'Sustainable Charter',
    text: 'Publication of the ATELIER Sustainable Charter: regenerative sourcing, zero-landfill production, and a lifetime repair programme for every garment sold.',
  },
  {
    year: '2024',
    title: 'New York Maison',
    text: 'Opening of our first American maison on the Upper East Side, extending the Lyon tradition of made-to-order appointments to a new continent.',
  },
]
